import { CardPost } from 'components/CardPost'
import { GridPost } from 'components/GridPost'
import { NavBar } from 'components/NavBar'
import Head from 'next/head'
export default function Home () {
  return (
    <>
      <Head>
        <title>
          JAMSTCK | BLOG
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&display=swap"
        rel="stylesheet"/>
      </Head>
      <NavBar/>
      <div className="global-container">
        <section className="section-welcome spacing-section">
            <article className="section-welcome__course">
              <h1>
                Cursos de React desde $29.99
              </h1>
              <div>

              </div>
            </article>
            <article className="section-welcome__info-course">
              <span>Martes 05 2021</span>
              <h2>
                La herramienta  #1 para el desarrollo frontent
              </h2>
              <p>
                React es la mejor herramienta para el desarrollo de aplicaciones web.
                Este curso te llevara a traves de una serie de pasos para crear una aplicacion web
                de forma rapida y sencilla.
              </p>
            </article>
        </section>

        <main>
          <GridPost title="Últimos post añadidos" >
            <CardPost
              date="Martes 05 2021"
              title="La herramienta  #1 para el desarrollo frontent"
              description="React es la mejor herramienta para el desarrollo de aplicaciones web."
            />
            <CardPost
              date="Martes 05 2021"
              title="La herramienta  #1 para el desarrollo frontent"
              description="React es la mejor herramienta para el desarrollo de aplicaciones web."
            />
            <CardPost
              date="Martes 05 2021"
              title="La herramienta  #1 para el desarrollo frontent"
              description="React es la mejor herramienta para el desarrollo de aplicaciones web."
            />
            <CardPost
              date="Martes 05 2021"
              title="La herramienta  #1 para el desarrollo frontent"
              description="React es la mejor herramienta para el desarrollo de aplicaciones web."
            />
            <CardPost
              date="Martes 05 2021"
              title="La herramienta  #1 para el desarrollo frontent"
              description="React es la mejor herramienta para el desarrollo de aplicaciones web."
            />
          </GridPost>
        </main>
      </div>

      <style jsx>{`
        .section-welcome{
          margin-top: 10rem;
          display: flex;
          justify-content: center;
          gap: 4rem;
          article{
            width: 98rem;
          }
          &__course{
            h1{
              font-size: 7rem;
              margin-bottom: 2rem;
            }
            div{
              width: 100%;
              height: 500px;
              border-radius: 1rem;
              background-image: var(--bg-gradient);
            }
          }

          &__info-course{
            span{
              color: var(--description-color);
              font-size: 1.8rem;
            }
            h2{
              font-size: 8rem;
              margin: 1rem 0;
            }

            p{
              font-size: 3rem;
              color: var(--description-color);
            }
          }

        }

        @media (max-width: 796px){
          .section-welcome{
            &__info-course{
              h2{
                font-size: 3.5rem;
              }
              p{
                font-size: 2rem;
              }
            }

            &__course{
              h1{
                font-size: 3.5rem;
              }
            }
          }
        }

        @media (max-width: 1055px){
          .section-welcome{
            flex-wrap: wrap-reverse;

            &__course{
              text-align: center;
            }
          }
        }
      
      `}</style>
    </>
  )
}
