import { NavBar } from 'components/NavBar'
import Head from 'next/head'
export default function Home () {
  return (
    <div>
      <Head>
        <title>
          JAMSTCK | BLOG
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500;700&display=swap"
        rel="stylesheet"/>
      </Head>
      <NavBar/>
      <h1>
        lorem
      </h1>
    </div>
  )
}
