import { NavBar } from 'components/NavBar'
import Head from 'next/head'
export default function Home () {
  return (
    <div>
      <Head>
        <title>
          JAMSTCK | BLOG
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
    </div>
  )
}
